import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, Check, ChevronRight } from 'lucide-react'
import { CTA, DetailMeta, EventGrid, MediaPlaceholder, PageShell } from '@/components/acm-site'
import { events, getEvent } from '@/lib/site-data'

export function generateStaticParams() { return events.map(event => ({ eventId: event.id })) }

export default async function EventDetail({ params }: { params: Promise<{ eventId: string }> }) { const { eventId } = await params; const event = getEvent(eventId); if (!event) notFound(); const related = events.filter(item => item.id !== event.id).slice(0, 2); return <PageShell><article className="mx-auto max-w-7xl px-5 pb-10 pt-36 sm:px-8"><Link href="/events" className="inline-flex items-center gap-2 text-xs text-slate-500 hover:text-white"><ArrowLeft size={14} /> Back to events</Link><div className="mt-12 grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-acm">{event.tags.join(' / ')}</p><h1 className="mt-5 max-w-4xl font-display text-4xl font-bold leading-tight tracking-tight text-white sm:text-6xl text-balance">{event.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400">{event.description}</p></div><MediaPlaceholder label={event.imageLabel} large /></div><div className="mt-12"><DetailMeta event={event} /></div><div className="grid gap-12 py-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="label">Event highlights</p><ul className="mt-5 space-y-4">{event.highlights.map(highlight => <li key={highlight} className="flex gap-3 text-sm leading-6 text-slate-300"><Check size={17} className="mt-1 shrink-0 text-acm" />{highlight}</li>)}</ul></div><div><p className="label">Photo gallery</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{Array.from({ length: Math.max(event.galleryCount, 1) }, (_, index) => <MediaPlaceholder key={index} label={event.placeholder ? event.imageLabel : `${event.imageLabel} ${index + 1}`} />)}</div></div></div><div className="border-t border-white/10 pt-10"><p className="label">Keep exploring</p><div className="mt-5 grid gap-5 md:grid-cols-2"><EventGrid items={related} /></div></div></article><CTA /></PageShell> }
